
version: 2

models:
  - name: fact_orders
    description: "Order fact table"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null

  - name: dim_products
    description: "Product dimension table"
    columns:
      - name: product_id
        tests: 
          - unique
          - not_null

  - name: dim_customers
    description: "Customer dimension table"
    columns:
      - name: user_id
        tests:
          - unique
          - not_null

  